Changing diagram pngs to svgs
alphagov/govuk-design-system pull request #1440
Opened 2021-01-04 13:57 UTC by CharlotteDowns

This is part of the work related to finding out whether current diagrams are accessible #1397

2021-01-04 15:53 UTC, EoinShaughnessy approved these changes
Looks good :)

2021-01-04 15:58 UTC, 36degrees requested changes

2021-01-04 15:58 UTC, 36degrees commented on src/patterns/check-a-service-is-suitable/index.md.njk
> +![‘Check a service is suitable’ flow diagram. Contains an introduction page followed by a series of simple questions. If at any point a user is deemed not eligible for the service they will be pointe
The filename of the new SVG is `check-a-service-suitable-flow.svg` – without the `-is-` – so either this needs updating or the file needs renaming.

(This is why the tests are failing at the minute)

2021-01-06 09:49 UTC, 36degrees approved these changes
Looks good to me! 👍🏻

2021-01-13 15:15 UTC, merged