Update index.md.njk
alphagov/govuk-design-system pull request #1445
Opened 2021-01-09 04:26 UTC by guyhickling

The following two lines are mutually contradictory:
- repeat information from the page
- include extra information not on the page
What you should say is don't include extra info that isn't showing in the image!

2021-01-14 11:47 UTC, CharlotteDowns requested changes

2021-01-14 11:47 UTC, CharlotteDowns commented on src/styles/images/index.md.njk
> +- include extra information not in the image
Suggestion: 
```suggestion
- include additional information not mentioned on the page
```

I think the aim of this line is to make sure all users can receive the same information regardless of whether they are using assistive technologies. Equally, the repetition of content to a user using assistive technology could be confusing and potentially perceived as an error.

2021-01-19 14:08 UTC, CharlotteDowns approved these changes

2021-01-19 14:13 UTC, calvin-lau-gds approved these changes

2021-01-19 14:13 UTC, 36degrees approved these changes
Thanks @guyhickling 👍🏻

2021-01-19 14:16 UTC, 36degrees commented
I've rebased to bring in the changes from #1442 so that the required status checks pass – although I think [GitHub is currently having issues](https://www.githubstatus.com/incidents/rk5rhrklkdk3) so the pull request has not updated yet.

2021-01-19 16:54 UTC, merged