Explain that Friday call is on pause
alphagov/govuk-design-system pull request #3032
Opened 2023-08-09 15:01 UTC by calvin-lau-sig7

2023-08-09 15:12 UTC, kellylee-gds commented
@calvin-lau-sig7 thanks for this! I'm just finalising the feedback survey - aiming to send it out tomorrow, then we can hit merge on this.

Do you reckon update the feedback link to go to the survey or keep it linking to our support channels?

2023-08-09 15:44 UTC, calvin-lau-sig7 commented
Oh, let's put the survey link in! We can merge it in this PR.

2023-08-10 07:54 UTC, colinrotherham commented
@calvin-lau-sig7 I've rebased this with https://github.com/alphagov/govuk-design-system/pull/3031 to pass the Prettier formatting check

2023-08-21 14:10 UTC, kellylee-gds requested changes
Once we have added a link to the survey then we can merge

2023-08-23 15:25 UTC, kellylee-gds approved these changes

2023-08-23 15:31 UTC, calvin-lau-sig7 commented on src/community/index.md
> +      <p>We regularly host informal chats with our community. We've currently paused our usual fortnightly catchup call whilst we work on improving the way we have these conversations with our commun
```suggestion
      <p>We regularly host informal chats with our community.</p>
      <p>We've currently paused our usual fortnightly catchup call whilst we work on improving the way we have these conversations with our community.</p>
      <p>We're keen to hear what you'd like to see and encourage you to <a href="https://surveys.publishing.service.gov.uk/s/1YTI43/">take our survey</a>.</p>
```

2023-08-23 15:38 UTC, merged